---
title: "204problemset2"
author: "Claire Madden"
date: "4/25/2019"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#set up 
library(tidyverse)
library(reconPlots)

#read in data
gasdata <- read_csv("Gas_Data.csv")

#change column headers to be more simple
names(gasdata) <- c("price", "q_low", "q_high")


```


1. What is the aggregate daily demand curve for gasoline in France? What is the supply curve for gasoline? What is the “benefit” to consumers under the status quo? What is the “benefit” to producers under the status quo? What is the environmental cost under the status quo?

```{r}
#need to find: high demand curve, low demand curve, aggregate demand curve, supply curve (mpc), environmental cost curve (mec) 

#high linear model demand curve:

d_high <- lm(price ~ q_high, data = gasdata)
summary(d_high)
#p=a(q)+b
#p= -0.0001297(q) + 23.39

#saving output numbers for use later
a_high <- d_high$coefficients[2]
b_high <- d_high$coefficients[1]

#high demand curve function p=a*q+b
demand_high <- function(x){a_high*x + b_high}

#variables for high demand curve q=p/a - b/a
a_high1 <- (1/a_high)
b_high1 <- (-b_high/a_high)


#low demand curve:

d_low <- lm(price ~ q_low, data = gasdata)
summary(d_low)
#p=a(q)+b
#p= -0.0001355(q) + 21.99

#saving output numbers for use later
a_low <- d_low$coefficients[2]
b_low <- d_low$coefficients[1]

#low demand curve function p=a*q+b
demand_low <- function(x){a_low*x + b_low}

#variables for low demand curve q=p/a - b/a
a_low1 <- (1/a_low)
b_low1 <- (-b_low/a_low)




#combine high and low variables to get aggregate 
a_agg <- a_high1 + a_low1
b_agg <- b_high1 + b_low1

#rearrage to get p=
a_agg1 <- (1/a_agg)
b_agg1 <- (-b_agg/a_agg)

agg_demand <- function(x){a_agg1*x + b_agg1}

#need to know what q equals when p is 21.99085 for aggregate demand curve


#supply curve (mpc)
supply <- 5/((5-b_agg1)/(a_agg1))

#supply function
supply_curve <- function(x){supply*x}

#environmental cost
mec <- function(x){0*x + 2}

#social cost
msc <- function(x){supply*x + 2}


#graph both demand functions on the same axes
allcurves <- ggplot(data.frame(x = c(7000, 500000)), aes(x = x)) +
  stat_function(fun = demand_low, color = "cadetblue4") +
  stat_function(fun = demand_high, color = "orchid4")+
  stat_function(fun = agg_demand, color = "tomato3")+
  stat_function(fun = mec, color = "turquoise")+
  stat_function(fun = msc, color = "gold")+
  stat_function(fun = supply_curve, color = "olivedrab4")+
  scale_y_continuous(limits = c(0,30), expand = c(0,0))+
  scale_x_continuous(limits = c(0,400000), expand = c(0,0))


allcurves

```

```{r}

x_range <- 0:500000

#intersection of aggregate demand and high demand curves
kink <- curve_intersect(agg_demand, demand_high, empirical = FALSE, domain = c(min(x_range), max(x_range))) 

kink

kink_q <- kink$x

kink_p <- kink$y

#intersection of supply and high demand
int_supp_highd <- curve_intersect(supply_curve, demand_high, empirical = FALSE, domain = c(min(x_range), max(x_range)))

int_supp_highd

int_supp_highd_q <- int_supp_highd$x

int_supp_highd_p <- int_supp_highd$y

#intersection of supply and low demand

int_supp_lowd <- curve_intersect(supply_curve, demand_low, empirical = FALSE, domain = c(min(x_range), max(x_range)))

int_supp_lowd

int_supp_lowd_q <- int_supp_lowd$x

int_supp_lowd_p <- int_supp_lowd$y


#intersection of supply and agg demand

int_supp_aggd <- curve_intersect(supply_curve, agg_demand, empirical = FALSE, domain = c(min(x_range), max(x_range)))

int_supp_aggd

int_supp_highd_q <- int_supp_aggd$x

int_supp_highd_p <- int_supp_aggd$y


#intersection of msc and agg demand

int_msc_aggd <- curve_intersect(msc, agg_demand, empirical = FALSE, domain = c(min(x_range), max(x_range)))

int_msc_aggd
                                
int_msc_aggd_q <- int_msc_aggd$x

int_msc_aggd_p <- int_msc_aggd$y


```


```{r}
#low demand benefit under status quo

base_cs_low <- b_low - int_supp_lowd_p
height_cs_low <- int_supp_lowd_q

cs_low <- (1/2)*base_cs_low*height_cs_low

cs_low


base_ps_low <- int_supp_lowd_p
height_ps_low <- int_supp_lowd_q

ps_low <- (1/2)*base_ps_low*height_ps_low

ps_low


#high demand benefit under status quo

base_cs_high <- b_high - int_supp_highd_p
height_cs_high <- int_supp_highd_q

cs_high <- (1/2)*base_cs_high*height_cs_high

cs_high


base_ps_high <- int_supp_highd_p
height_ps_high <- int_supp_highd_q

ps_high <- (1/2)*base_ps_high*height_ps_high

ps_high



```

```{r}
#environmental cost under status quo

base_tec <- int_msc_aggd_q
height1_tec <- 2
height2_tec <- int_msc_aggd_p

tec <- base_tec*((height1_tec+height2_tec)/2)

tec


```


